version: "3.6"
services:
  portfolio:
    build:
      context: ../..
      dockerfile: devops/prod-portfolio/app/Dockerfile
    restart: always
    expose:
      - "80"
      - "443"
    environment:
      - VIRTUAL_HOST=${PORTFOLIO_HOST}
      - VIRTUAL_PORT=80
      - LETSENCRYPT_HOST=${PORTFOLIO_HOST}
      - LETSENCRYPT_EMAIL=${LETSENCRYPT_EMAIL}
  nginx:
    image: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    expose:
      - 80
    depends_on:
      - portfolio
    links:
      - portfolio

networks:
  default:
    external:
      name: nginx-proxy
